### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by DiddiLeija** [DiddiLeija/diddi-and-eli#3]
I'm preparing a TODO with every feature I want to add in version `1.0.0`:

- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [ ] #9
- [ ] #10
- [ ] #11
- [ ] Better storytelling
  - It should be possible to easily understand the game's storyline
  - We should add better animations to the game's story scenes
- [ ] Barriers
  - A type of block that allows the player to move to the right across it, but not left? It would be handy for some level situations
  - **Would be superseeded by #10**
- [x] Stable world generation
- [x] Multiplayer fixes
- [x] Polished "jump" physics (_making them more jump-ish and less fly-ish_)
- [x] Coins
- [x] Clouds
- [ ] Level/scenes setup
  - [x] Menu
  - [x] Intro sequence 
  - [x] Level 1
  - [x] Level 2
  - [x] Level 3
  - [x] Level 4
  - [x] Pre-boss sequence
  - [ ] Level 5 (Final boss battle)
    - [ ] Coding for the Scaler character, intended to be a real challenge.
  - [x] Closing sequence
  - [x] Death sequences (when a player dies, instead of moving straight to the menu)
- [x] Introduction of NPCs
- [x] A "save" mechanic to save progress (and leave the "roguelike" system of the game) or either start from scratch
  - [x] Save the last-played level
  - [x] Save a coin count
  - [x] Reset the data if we start again
  - [ ] Save other data?
- [x] CI integrations
- [ ] A GitHub wiki
- [x] A stronger linting strategy
- [ ] Limited bullets per player (+ "bullet packs" to refill)
- [x] Player info/coin counter on ~~top~~ the bottom of the screen [^1]
- [x] More player options?
- [ ] Sprite shading? -- this is a WIP idea I have for making the sprites more visible.

Abandoned/rejected feats:

- [x] ~~"Skins customization" (on a similar way to DiddiLeija/diddi-and-the-bugs#137)~~
  - I left this idea since the game adopted a storyline (which means a static level order). I may take the idea back on a further project, such as the abandoned `DiddiLeija/diddi-platforms` :wink:
- **Left to a future release** - These are nice ideas, but I'd like to implement them on a future release. By now, they'll keep as `TODO`s :wink:
  - [x] Bullets sent by mobs
  - [x] Moving slimehorns

[^1]: Otherwise, why would I have coins in the game? :smile:

**Comment by DiddiLeija** [comment]
By now, and due to the "slow development" of the game, I'll use no PRs by now, and instead I'll commit directly to `main` (starting with 3862d667faefde2cb6547679b7af4e975c5f8bb1) :wink:

**Comment by DiddiLeija** [comment]
At this point (de1599b1b65590ebff8b873efefc513461a3d154) I'd say Level 1/5 is ready to go! :tada: :partying_face:
There's still a lot to do, but we have a progress! :)

**Comment by DiddiLeija** [comment]
At this point (01cef82) Level 2 is live! :tada:
However, I'm having trouble with changing from Level 1 to 2, due to collision detections :/

**Comment by DiddiLeija** [comment]
Now that #4 and #5 are fixed, and after commit 97f5d11ed4d46c2b57eb34401235fa273f06c0a3, both levels 2 and 3 are now available to play :partying_face:

**Comment by DiddiLeija** [comment]
Ok, so Level 4 is officially live after 4c3b839!

---

Also, I've added an advanced option to create levels -- gradient colors!

Before:
<img width="300" alt="image" src="https://github.com/DiddiLeija/diddi-and-eli/assets/83621221/69ddb737-5c93-4a02-9f24-00fe18502cf3">

After:
<img width="300" alt="image" src="https://github.com/DiddiLeija/diddi-and-eli/assets/83621221/c919405e-5afa-477e-9bf7-e35f8294e349">

It's still a WIP, and I'll make a few adjustments (colors, rendering, etc) as I develop it.
